memo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: HOST
    port: POST
    database: DATABASE
    username: USERNAME
    password: PASSWORD
  jwt:
    # jwt签名加密时使用的密钥
    secret-key: SECRET_KEY
    # jwt过期时间 2小时 (=2 * 60 * 60 * 1000)
    ttl: 7200000
  front:
    ip:
      - http://localhost:3000
  exclude:
    path:
      - /user/login
      - /user/register