/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CommentsIndexRouteImport } from './routes/comments/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'

const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsIndexRoute = CommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/categories/': typeof CategoriesIndexRoute
  '/comments/': typeof CommentsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/categories': typeof CategoriesIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/login': typeof LoginIndexRoute
  '/notes': typeof NotesIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/categories/': typeof CategoriesIndexRoute
  '/comments/': typeof CommentsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/categories/'
    | '/comments/'
    | '/login/'
    | '/notes/'
    | '/photos/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/categories' | '/comments' | '/login' | '/notes' | '/photos' | '/users'
  id:
    | '__root__'
    | '/categories/'
    | '/comments/'
    | '/login/'
    | '/notes/'
    | '/photos/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CommentsIndexRoute: typeof CommentsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/': {
      id: '/comments/'
      path: '/comments'
      fullPath: '/comments/'
      preLoaderRoute: typeof CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CategoriesIndexRoute: CategoriesIndexRoute,
  CommentsIndexRoute: CommentsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
